# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sNl_fk128c0Odl62m8FcIJBo_WwUIlUl
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

train_df = pd.read_csv("/content/drive/MyDrive/train.csv")
test_df = pd.read_csv("/content/drive/MyDrive/test.csv")

def map_binary(x):
    if x == "no stress":
        return 0
    else:
        return 1

train_df["Stress"] = train_df["condition"].apply(map_binary)
test_df["Stress"] = test_df["condition"].apply(map_binary)

print(train_df["Stress"].value_counts())

def add_features(df):
    df["LF_HF_ratio"] = df["LF"] / (df["HF"] + 1e-6)

    sd_col = "SDRR" if "SDRR" in df.columns else "SDNN"
    df["HRV_balance"] = df["RMSSD"] / (df[sd_col] + 1e-6)

    if "SD1" in df.columns and "SD2" in df.columns:
        df["variability"] = df["SD1"] + df["SD2"]
    else:
        df["variability"] = 0

    return df

train_df = add_features(train_df)
test_df = add_features(test_df)

features = [
    "MEAN_RR", "RMSSD", "SDRR", "pNN50",
    "LF", "HF", "LF_HF", "VLF",
    "LF_HF_ratio", "HRV_balance", "variability"
]

features = [f for f in features if f in train_df.columns]

X_train = train_df[features]
y_train = train_df["Stress"]

X_test = test_df[features]
y_test = test_df["Stress"]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    n_jobs=-1,
    random_state=42
)

model.fit(X_train_scaled, y_train)

from sklearn.metrics import classification_report

y_pred = model.predict(X_test_scaled)

print(classification_report(y_test, y_pred))

import pandas as pd
import numpy as np

label_map_reverse = {
    0: "NO STRESS",
    1: "STRESS"
}

# Example stress sample
sample = [[
    700,
    10,
    60,
    0.3,
    1500,
    20,
    75,
    3000,
    75,
    0.12,
    100
]]

sample_df = pd.DataFrame(sample, columns=features)
sample_scaled = scaler.transform(sample_df)

prediction = model.predict(sample_scaled)[0]

print("Prediction:", label_map_reverse[prediction])

import pandas as pd

label_map_reverse = {
    0: "NO STRESS",
    1: "STRESS"
}

print("✅ Testing using real dataset samples\n")

for label in [0, 1]:

    sample_row = test_df[test_df["Stress"] == label].iloc[0]

    sample = sample_row[features].values.reshape(1, -1)
    sample_df = pd.DataFrame(sample, columns=features)

    sample_scaled = scaler.transform(sample_df)
    pred = model.predict(sample_scaled)[0]

    print("🔹 ----------------------")
    print("Actual:", label_map_reverse[label])
    print("Predicted:", label_map_reverse[pred])

for i in range(5):
    sample = X_test.iloc[i].values.reshape(1, -1)
    sample_df = pd.DataFrame(sample, columns=features)
    sample_scaled = scaler.transform(sample_df)

    pred = model.predict(sample_scaled)[0]

    print("Predicted:", label_map_reverse[pred])

import pandas as pd

# Label mapping
label_map_reverse = {
    0: "NO STRESS",
    1: "STRESS"
}

# -------------------------------
# GET REAL STRESS SAMPLE
# -------------------------------
sample_row = test_df[test_df["Stress"] == 1].iloc[0]

# Extract features
sample = sample_row[features].values.reshape(1, -1)

# Convert to DataFrame (important)
sample_df = pd.DataFrame(sample, columns=features)

# Scale
sample_scaled = scaler.transform(sample_df)

# Predict
prediction = model.predict(sample_scaled)[0]

print("✅ Prediction:", label_map_reverse[prediction])

import pandas as pd

label_map_reverse = {
    0: "NO STRESS",
    1: "STRESS"
}

print("✅ Reliable Testing Using Real Data\n")

for label in [0, 1]:
    sample_row = test_df[test_df["Stress"] == label].iloc[0]

    sample = sample_row[features].values.reshape(1, -1)
    sample_df = pd.DataFrame(sample, columns=features)
    sample_scaled = scaler.transform(sample_df)

    pred = model.predict(sample_scaled)[0]

    print("🔹 ----------------------")
    print("Actual:", label_map_reverse[label])
    print("Predicted:", label_map_reverse[pred])