# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qVILfl-pHm4_w4NDMHFeNB4C4NT05_d
"""

from sklearn.ensemble import IsolationForest

anomaly_model = IsolationForest(contamination=0.1)

anomaly_model.fit(X_train_scaled)

joblib.dump(anomaly_model, "anomaly_model.pkl")

print("Anomaly model updated!")

X_train = train_df[features]
y_train = train_df["Stress"]

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

train_df = pd.read_csv("/content/drive/MyDrive/train.csv")
test_df = pd.read_csv("/content/drive/MyDrive/test.csv")

print("Data loaded!")

def map_binary(x):
    if x == "no stress":
        return 0
    else:
        return 1

train_df["Stress"] = train_df["condition"].apply(map_binary)
test_df["Stress"] = test_df["condition"].apply(map_binary)

print(train_df["Stress"].value_counts())

def add_features(df):
    df["LF_HF_ratio"] = df["LF"] / (df["HF"] + 1e-6)

    sd_col = "SDRR" if "SDRR" in df.columns else "SDNN"
    df["HRV_balance"] = df["RMSSD"] / (df[sd_col] + 1e-6)

    if "SD1" in df.columns and "SD2" in df.columns:
        df["variability"] = df["SD1"] + df["SD2"]
    else:
        df["variability"] = 0

    return df

train_df = add_features(train_df)
test_df = add_features(test_df)

print("Feature engineering done!")

features = [
    "MEAN_RR", "RMSSD", "SDRR", "pNN50",
    "LF", "HF", "LF_HF", "VLF",
    "LF_HF_ratio", "HRV_balance", "variability"
]

features = [f for f in features if f in train_df.columns]

X_train = train_df[features]
y_train = train_df["Stress"]

X_test = test_df[features]
y_test = test_df["Stress"]

print("Features selected:", features)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaling done!")

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    n_jobs=-1,
    random_state=42
)

model.fit(X_train_scaled, y_train)

print("Model trained!")

from sklearn.metrics import classification_report

y_pred = model.predict(X_test_scaled)

print(classification_report(y_test, y_pred))

baseline = {}

for col in features:
    baseline[col] = {
        "mean": train_df[col].mean(),
        "std": train_df[col].std()
    }

print("Baseline created!")

from sklearn.ensemble import IsolationForest

anomaly_model = IsolationForest(contamination=0.1)

anomaly_model.fit(X_train_scaled)

print("Anomaly model trained!")

import pandas as pd

label_map_reverse = {
    0: "NO STRESS",
    1: "STRESS"
}

for label in [0, 1]:
    sample_row = test_df[test_df["Stress"] == label].iloc[0]

    sample = sample_row[features].values.reshape(1, -1)
    sample_df = pd.DataFrame(sample, columns=features)

    sample_scaled = scaler.transform(sample_df)
    pred = model.predict(sample_scaled)[0]

    print("\n🔹 -------------------")
    print("Actual:", label_map_reverse[label])
    print("Predicted:", label_map_reverse[pred])

sample = [[
    700, 10, 60, 0.3,
    1500, 20, 75, 3000,
    75, 0.12, 100
]]

sample_df = pd.DataFrame(sample, columns=features)
sample_scaled = scaler.transform(sample_df)

prediction = model.predict(sample_scaled)[0]

print("Manual Input Prediction:", label_map_reverse[prediction])

import joblib

joblib.dump(model, "stress_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(baseline, "baseline.pkl")
joblib.dump(anomaly_model, "anomaly_model.pkl")

print("All files saved!")